### ISSUE TITLE
How to build mayavi on top of the notebook image?

### ISSUE THREAD

**Issue by brunorpinho** [jupyter/docker-stacks#421] opened 2017-07-28 21:23 UTC
Hello,

Are there any solutions for using `mayavi` for 3D visualizations in the `scipy-notebook` containers?

**Q&A:**

**What docker image you are using?**

I am building `mayavi` on top of `jupyter/scipy-notebook` using this script:

```
FROM jupyter/scipy-notebook

USER $NB_USER

RUN conda install --quiet --yes -p $CONDA_DIR/envs/python2 python=2.7 \
	'mayavi=4.5*'

RUN bash -c "source activate python2 && jupyter nbextension install --py mayavi --user"
```

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it --rm -p 8889:8888 jupyter/scipy-notebook-Mayavi`

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://localhost:8889
2. Start a jupyter notebook
3. Run:
```
from mayavi import mlab

mlab.init_notebook()

mlab.test_contour3d()
```
**What do you expect to happen?**

Open a 3D visualization inside the notebook.

**What actually happens?**

The kernel crashes with the following error:

```
Notebook initialized with x3d backend.
ERROR: In ../Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 301
vtkXOpenGLRenderWindow (0x20f1130): bad X server connection. DISPLAY=[I 21:23:34.278 NotebookApp] KernelRestarter: restarting kernel (1/5)
kernel bc3fcd2f-61ba-441a-b96a-f7bde811544f restarted

```

**Comment by cancan101** [comment] 2017-10-10 17:18
Why was the issue closed?

**Comment by brunorpinho** [comment] 2017-10-10 19:38
@cancan101 just because it was a duplicate, but I'm still looking for a solution. Should I just leave it opened?

**Comment by cancan101** [comment] 2017-10-10 19:40
Duplicate of what? I would link to other issue or leave this one open.

**Comment by parente** [comment] 2019-03-31 19:48
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in this topic can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.

**Closed by parente** 2019-03-31 19:48 UTC
Labels: help wanted

**Comment by kaczmarj** [comment] 2020-07-21 03:52
I solved this by running jupyter notebook with xvfb.

```
xvfb-run jupyter-notebook
```
