### ISSUE TITLE
r

### ISSUE THREAD

**Issue by galenbancroft** [jupyter/docker-stacks#929] opened 2019-08-21 18:45 UTC
Hi! Thanks for using the Jupyter Docker Stacks.

Please review the following guidance about how to ask questions, contribute changes, or report bugs in the Docker images maintained here.

1. If you have a general question about using these Docker images or with Jupyter + Docker in general, please post your question in the [Jupyter Discourse Q&A section](https://discourse.jupyter.org/c/questions) so that it can be seen, discussed, and hopefully answered by the community.

2. If you are looking to contribute to the images, please see the [Contributor's Guide](http://jupyter-docker-stacks.readthedocs.io/en/latest/#) in the documentation for our preferred processes.

3. If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

Example: `jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8889:8888 jupyter/all-spark-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8889
2. Start an R noteobok
3. ...

**What do you expect to happen?**

Example: ggplot output appears in my notebook.

**What actually happens?**

Example: No output is visible in the notebook and the notebook server log contains messages about ...

**Comment by romainx** [comment] 2020-02-08 20:00
Hello,

I've just run the `all-spark-notebook:latest` as you describe.

```bash
$ docker run -it --rm -p 8889:8888 jupyter/all-spark-notebook:latest
```

Then I've started a `R` notebook and typed the following `ggplot2` example:

```R
library(ggplot2)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

And here is the output.
Could you please retry -- I know that the R packages have recently been updated on this stack?

<img width="513" alt="Untitled_-_Jupyter_Notebook" src="https://user-images.githubusercontent.com/7131913/74091251-b5ed8680-4ab5-11ea-9cdc-af46940faea5.png">

Best

**Comment by romainx** [comment] 2020-02-26 20:43
@galenbancroft could you please check if it's OK for you and close the issue if it's the case?
Many thanks

**Comment by romainx** [comment] 2020-03-11 19:55
We have no answer and everything seems to be working fine. In consequence, I'm going to close it. Feel free to open a new issue with the tag, steps to reproduce, etc. if you think something does not work as expected.
Best.

**Closed by romainx** 2020-03-11 19:55 UTC
