### ISSUE TITLE
R missing from the New Notebook section and JupyterLab Launcher page

### ISSUE THREAD

**Issue by lab1702** [jupyter/docker-stacks#1447] opened 2021-08-26 15:11 UTC
**What docker image you are using?**

jupyter/datascience-image

**What complete docker command do you run to launch the container (omitting sensitive values)?**

docker run --rm -ti -p 8888:8888 jupyter/datascience-notebook

and

docker run --rm -ti -p 8888:8888 -e JUPYTER_ENABLE_LAB=yes jupyter/datascience-notebook

**What steps do you take once the container is running to reproduce the issue?**

In old style jupyter, open the New menu
In JupyterLab, it's visible on Launcher page as you connect

**What do you expect to happen?**

R notebook, R console to be available in JupyterLab and R kernel to be available in old style notebook

**What actually happens?**

R is missing.

**Comment by sknauff** [comment] 2021-08-30 14:31
I have experience the same issue. R doesn't show up in kernel selection drop down in JupyterLab either. I think that the latest working image on DockerHub that includes R in JupyterLab is `jupyter/datascience-notebook:2021-08-25`?

**Comment by consideRatio** [comment] 2021-08-31 21:05
I'm closing this as a duplicate of #1450 that had some technical details of relevance even though this was opened first. Thanks for reporting this!

**Closed by consideRatio** 2021-08-31 21:05 UTC
Labels: type:Bug

**Comment by mathbunnyru** [comment] 2021-09-01 09:54
I checked - it works for me with latest image.

**Comment by mathbunnyru** [comment] 2021-09-01 09:54
Thanks for reporting the issue and investigating when it broke 👍
