### ISSUE TITLE
M1 Apple's MacBooks support

### ISSUE THREAD

**Issue by AKJHK2021** [jupyter/docker-stacks#1238] opened 2021-02-13 00:33 UTC
Is there a chance to have the same docker image that runs on M1 Apple's MacBooks..

Thanks!

**Comment by romainx** [comment] 2021-02-13 06:51
Hello,

Yes, in fact I think we need to build an ARM image. If so, it's basically what I've drafted in the PR #1202. You can have a look if you are interested. It was not merged since it requires some additional work and since we had other priorities at this time. But it's definitely possible.

Another option you have right now is to use emulation to run the current AMD64 (X86) images. Have a look at [Apple M1 Tech Preview](https://docs.docker.com/docker-for-mac/apple-m1/)

> Not all images are available for ARM64. You can add `—platform linux/amd64` to run an Intel image under emulation.

Your feedback will be appreciated.

Best

**Comment by manics** [comment] 2021-04-13 10:15
This looks like a duplicate of https://github.com/jupyter/docker-stacks/issues/1019. Since that issue includes work from others who've done their own builds is it worth closing this issue, and modifying the title of https://github.com/jupyter/docker-stacks/issues/1019 to make it clear it's for all ARM platforms?

**Comment by romainx** [comment] 2021-04-17 07:18
@manics good remark I'm closing it in favor of #1019.

**Closed by romainx** 2021-04-17 07:18 UTC
Labels: type:Enhancement
