### ISSUE TITLE
failed to load jupyterlab-git server extension

### ISSUE THREAD

**Issue by JessicaBarh** [jupyter/docker-stacks#1228] opened 2021-02-03 21:35 UTC
**What docker image you are using?**

jupyter/datascience-notebook:r-4.0.3

**What complete docker command do you run to launch the container (omitting sensitive values)?**

docker run -p 8888:8888 jupyter/datascience-notebook:r-4.0.3

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://localhost:8888/lab
2. pip install --pre jupyterlab-git
3. verify install: jupyter server extension list && jupyter labextension list
4. refresh jupyterlab

**What do you expect to happen?**

see jupyterlab-git extensions in toolbar

**What actually happens?**

![image](https://user-images.githubusercontent.com/71149531/106812169-49ac5100-663d-11eb-8a75-7cc9b81046c3.png)

**Comment by mathbunnyru** [comment] 2021-02-04 13:56
I think this is an issue in the upstream.
https://github.com/jupyterlab/jupyterlab-git/issues/779

Docker-stacks have recently moved to jupyterlab 3.0, that's why some extensions need to update to work well with the stacks.

For now, if you don't need latest features, you can use an older image which still uses jupyterlab 2.0.

**Comment by jameslao** [comment] 2021-02-04 23:54
I'm facing the same issue even when installed on bare metal. Everything looks fine though.
```
$ sudo jupyter server extension list
Config dir: /root/.jupyter

Config dir: /usr/etc/jupyter

Config dir: /usr/local/etc/jupyter
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.7 OK
    jupyterlab_git enabled
    - Validating jupyterlab_git...
      jupyterlab_git 0.30.0b1 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK
    nbdime enabled
    - Validating nbdime...
      nbdime 3.0.0.b1 OK
```

**Comment by jameslao** [comment] 2021-02-04 23:57
Ah, it magically gets resolved after using `c.Spawner.cmd=["jupyter-labhub"]` in jupyterhub...

**Comment by JessicaBarh** [comment] 2021-02-05 00:00
> Ah, it magically gets resolved after using `c.Spawner.cmd=["jupyter-labhub"]` in jupyterhub...

Which file is that in?

**Comment by jameslao** [comment] 2021-02-05 00:02
> > Ah, it magically gets resolved after using `c.Spawner.cmd=["jupyter-labhub"]` in jupyterhub...
> 
> Which file is that in?

`/etc/jupyterhub/jupyterhub_config.py'

**Comment by JessicaBarh** [comment] 2021-02-05 17:05
Hi @jameslao! 
Can you share some more details on how you did this? Still not working with me :/
What docker-stacks image/tag are you using?  
How do you start up your jupyterlab?
Also I didn't have an existing "jupyterhub_config.py" file so I had to create it..did you need to do the same?

Thanks, any help would be very appreciated! 😄

**Comment by jameslao** [comment] 2021-02-05 17:09
> Hi @jameslao! 
> 
> Can you share some more details on how you did this? Still not working with me :/
> 
> What docker-stacks image/tag are you using?  
> 
> How do you start up your jupyterlab?
> 
> Also I didn't have an existing "jupyterhub_config.py" file so I had to create it..did you need to do the same?
> 
> 
> 
> Thanks, any help would be very appreciated! 😄 

Hi sorry I'm not using a docker image but a bare-metal installation with JupyterHub. ￼I am only in this thread because I was looking for the same symptom. Sorry again if I caused any confusion. ￼

**Comment by apeming** [comment] 2021-04-14 10:28
I'm facing the same issue on kubernetes

**Comment by apeming** [comment] 2021-04-16 02:45
> I'm facing the same issue on kubernetes

I pre install the jupyterlab-git in the basic-notebook and it works. Hope it can help

**Comment by mathbunnyru** [comment] 2021-04-18 16:18
@JessicaBarh @jameslao @apeming 

It seems that the upstream released a new version and the issue is closed now.

https://github.com/jupyterlab/jupyterlab-git/issues/779#issuecomment-821823380

Both pypi and conda already have the newest version:
https://pypi.org/project/jupyterlab-git/
https://anaconda.org/conda-forge/jupyterlab-git/files

Please, confirm, that version 0.30.0 works fine and I will close this issue.

**Comment by apeming** [comment] 2021-04-19 01:56
Still failed to load the jupyterlab-git server extension in docker image jupyter/scipy-notebook:8d32a5208ca1

![image](https://user-images.githubusercontent.com/17539850/115171256-3fa2d600-a0f5-11eb-8c99-bcc1c8a6e50c.png)

![image](https://user-images.githubusercontent.com/17539850/115171288-521d0f80-a0f5-11eb-84ee-b5c3a62cfcc1.png)

**Comment by mathbunnyru** [comment] 2021-04-20 16:15
I think I finally made it work!

I have the same issue, as you do if I install `jupyterlab-git` in already running jupyterlab.

But I have created a `Dockerfile` just like this:
```
FROM jupyter/datascience-notebook
RUN conda install jupyterlab-git
```

And built it `docker build -t my_tag ./`
And ran: `docker run -v SOME_GIT_FOLDER:/home/jovyan/ -p 8888:8888 my_tag`

And, it works!

**Comment by mathbunnyru** [comment] 2021-04-27 12:14
@JessicaBarh @jameslao @apeming
Please, use the solution I gave above and it should work fine.

**Closed by mathbunnyru** 2021-04-27 12:14 UTC
Labels: tag:Upstream
