### ISSUE TITLE
ImportError: PyArrow >= 0.8.0 must be installed; however, it was not found.

### ISSUE THREAD

**Issue by mjimcua** [jupyter/docker-stacks#921] opened 2019-08-05 14:09 UTC
I use last "jupyter/all-spark-notebook" image

Error raises when I run Pandas UDF in a pyspark notebook.

Example code:

```
import pandas as pd
import numpy as np
from pyspark.sql.types import *
from pyspark.sql.functions import pandas_udf
from pyspark.sql.functions import PandasUDFType

new_schema = StructType([
    StructField('field1', IntegerType(), True),
    StructField('field2', IntegerType(), True),
    ])

def pandas_udf_process(df_pd):
    return(df_df)

@pandas_udf(new_schema, functionType=PandasUDFType.GROUPED_MAP)
def udf_process(df): 
    return pandas_udf_process(df)
```
Error:

ImportError: PyArrow >= 0.8.0 must be installed; however, it was not found.

However, is intalled pyarrow 0.11.1 version, it can see in conda list inside container:

```
pyarrow                   0.11.1          py37hbbcf98d_1002    conda-forge
pycosat                   0.6.3           py37h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pycurl                    7.43.0.2         py37h16ce93b_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyrsistent                0.15.4           py37h516909a_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
```

**Comment by rkdarst** [comment] 2019-08-05 15:15
Hmm...

```
$ python3
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/__init__.py", line 54, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /opt/conda/lib/python3.7/site-packages/pyarrow/lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK5arrow6Status8ToStringB5cxx11Ev
```

This gives us something better searcheable... for example
https://github.com/conda-forge/pyarrow-feedstock/issues/58

I don't have more time now but one could check boost versions.

**Comment by evkoskib** [comment] 2019-10-06 19:46
A workaround is to pip uninstall pyarrow, and install it again in the all-spark-notebook.

Once I did that and restarted the kernel, I was able to import without errors.

**Comment by parente** [comment] 2020-01-20 04:56
Thanks for reporting. I'm going to close this as a dupe of #944. I know this issue was reported first, but #944 has more detail about a workaround.

**Closed by parente** 2020-01-20 04:56 UTC

**Comment by josedanielfd** [comment] 2020-03-28 00:42
I have done pip uninstall pyarrow and pip install pyarrow but still is not working...

Any suggestions?

**Comment by amol8052** [comment] 2023-03-28 14:19
![image](https://user-images.githubusercontent.com/62262957/228268436-b66f09e4-4a1d-4525-ba73-78e83e698d65.png)
this may help
