### ISSUE TITLE
Convert JDBC-Dataframe to Dataset is failing

### ISSUE THREAD

**Issue by iolbr** [jupyter/docker-stacks#578] opened 2018-03-12 16:01 UTC
Hi,
started to use the all-spark-notebook. Run into error while trying to convert dataframe into dataset.
**What docker image you are using?**

jupyter/all-spark-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**
PS C:\WINDOWS\system32> docker run -it --rm -p 8888:8888 --user root -e NB_UID=1000 -e NB_GID=100 -e GRANT_SUDO=yes -v C:/docker/jupyter:/home/jovyan/work jupyter/all-spark-notebook

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8888
2. Open scala notebook
3. Setup JDBC-Connection to postgres database (%AddDeps org.postgresql postgresql 42.2.1 --transitive --trace --verbose)
4. Get dataframe from db:
  val sql = "(select id from jobs where processing_state_id = 0) as subset"
  val jobsDF = spark.read.jdbc(postgres_jdbc_url,sql,connectionProperties)
  jobsDF.show(20)
  jobsDF.printSchema()

  +----+
|  id|
+----+
|3812|
|3813|
|3814|  

root
 |-- id: integer (nullable = false)
5. Trying to convert dataframe to dataset:
val sqlc = spark
import sqlc.implicits._

case class Project(id:Integer)
val jobsDS = jobsDF.as[Project]

Getting error:
Name: Unknown Error
Message: <console>:159: error: Unable to find encoder for type stored in a Dataset.  Primitive types (Int, String, etc) and Product types (case classes) are supported by importing spark.implicits._  Support for serializing other types will be added in future releases.
       val jobsDS = jobsDF.as[Project]
                             ^
**What do you expect to happen?**
Dataframe should be converted into Dataset

**What actually happens?**
Get an exception

**Comment by iolbr** [comment] 2018-03-17 08:51
Seems to no issue with the notebook. Build a test case in scala/spark directly and was able to reproduce it.

**Comment by parente** [comment] 2018-03-17 16:28
@iolbr If you do resolve this completely, would you mind posting a comment as to how for future readers? 

Is it OK to close this issue since the problem is with Scala / Spark and nothing related to the Jupyter docker images?

**Comment by parente** [comment] 2018-04-07 21:37
Closing this issue since it's inactive.

**Closed by parente** 2018-04-07 21:37 UTC
Labels: dependency

**Comment by iolbr** [comment] 2018-04-10 06:45
Looks like a dependency issue. I did upgrade my solution to latestet postgres JDBC driver 42.2.2 and created a new docker container with the jupyter notebook.
