### ISSUE TITLE
"jupyter notebook list" won't show running instances with custom NB_USER setting

### ISSUE THREAD

**Issue by sanketsarang** [jupyter/docker-stacks#1497] opened 2021-10-20 16:59 UTC
When starting a container with custom `NB_USER` setting, the `jupyter notebook list` command fails to capture the running instance. The running instances show only if the user is `jovyan`. 

## Works
```shell
user@server:~$ sudo docker run -d -p 8888:8888 --user root -e NB_USER=jovyan jupyter/base-notebook start-notebook.sh
b61dfab4b2b4263bf4379c2ab321d23401c4187c9a06421386fbcf1c68d32e6f

user@server:~$ sudo docker exec b61dfab4b2b4263bf4379c2ab321d23401c4187c9a06421386fbcf1c68d32e6f jupyter notebook list
Currently running servers:
http://0.0.0.0:8888/?token=7a228aefeed6246cbf47c4290c3540eaadbf9de5cb9e3d87 :: /home/jovyan
user@server:~$
```
## Does not work
The same command, with `NB_USER=hello` fails to capture the running instance.

```shell
user@server:~$ sudo docker run -d -p 8888:8888 --user root -e NB_USER=hello jupyter/base-notebook start-notebook.sh
6e20733afdd58d18f2983c4e90e280ca31d2c8af3106f4b9f078dec1f9fcc136

user@server:~$ sudo docker exec 6e20733afdd58d18f2983c4e90e280ca31d2c8af3106f4b9f078dec1f9fcc136 jupyter notebook list
Currently running servers:
user@server:~$ 
```

The returned list is empty, as if an instance of Jupyter is not running. However, an instance is running. This can be verified by running docker without the `-d` flag.

**Comment by ggaaooppeenngg** [comment] 2021-11-04 15:37
The environment variable maybe work at the build phase. You can use the dockerfile below to build an image with the custom user.
```docker
ARG BASE_CONTAINER=jupyter/scipy-notebook
FROM $BASE_CONTAINER
ARG NEW_USER="hello"

USER root

RUN echo "rename to $NEW_USER from $NB_USER" && \
    usermod -l $NEW_USER -d /home/$NEW_USER -m ${NB_USER} && \
    rm -rf /home/${NB_USER} && \
    chown -R $NEW_USER /home/$NEW_USER

ENV XDG_CACHE_HOME="/home/${NEW_USER}/.cache/"
ENV HOME="/home/${NEW_USER}"
ENV NB_USER=$NEW_USER

USER $NEW_USER
```

**Comment by consideRatio** [comment] 2021-11-04 15:42
@sanketsarang you need to use the `start.sh` script, otherwise the logic to consider NB_USER won't matter. See https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh.

**Comment by consideRatio** [comment] 2021-11-04 15:47
If you start a container with --user=root, and NB_USER=jovyan, it means the startup script will switch to the jovyan user after startup.

When you do `docker exec`, it will enter as the root user, because its a new session that is influenced by `--user=root`, but not by `NB_USER=jovyan` etc. So it sounds like you are reporting a failure for `jupyter notebook list` to list information about notebook servers running as another user.

I figure that may be intended behavior, to not report something run by other users. But, you could likely do...

```
sudo docker exec --user=jovyan 6e20733afdd58d18f2983c4e90e280ca31d2c8af3106f4b9f078dec1f9fcc136 jupyter notebook list
```

**Comment by mathbunnyru** [comment] 2022-02-04 09:41
I think @consideRatio's explanation is good and there was no comment after that, so I'm closing this issue.

**Closed by mathbunnyru** 2022-02-04 09:41 UTC
Labels: type:Question
