### ISSUE TITLE
Consider redoing all scripts with Xonsh

### ISSUE THREAD

**Issue by maresb** [jupyter/docker-stacks#1233] opened 2021-02-07 18:23 UTC
I've become a big fan of the [Xonsh](https://xon.sh/) shell scripting language. It allows for almost seamless mixing between Bash and Python. Thus you get the sanity of Python, but you can still simply run a command without needing `subprocess`.

I think it may provide a viable way forward for initiatives which have stalled out, such as #1052 and #1140.

**Comment by consideRatio** [comment] 2021-05-04 02:06
I like the idea of sticking with Makefile/bash/python even though I don't yet know of Xonsh. I have grown fond whatever tech that can be understood using well known tech as it reduce the threshold to maintain and contribute to a project.

**Comment by mathbunnyru** [comment] 2023-06-06 16:34
Hi @maresb!
Would you like to work on this feature? 😄

I think the most significant issues in our images reside in shell scripts currently (especially, in `start.sh`), and it would be nice to move to pure Python in the future, so to me, `xonsh` is an excellent intermediate step.
I think it might make fixing some issues easier.

**Comment by maresb** [comment] 2023-06-06 16:35
Hey @mathbunnyru, thanks for thinking of me! I'm going to pass on this one though. (I have too much other stuff going on already.)

**Comment by mathbunnyru** [comment] 2023-06-06 16:37
> Hey @mathbunnyru, thanks for thinking of me! I'm going to pass on this one though. (I have too much other stuff going on already.)

I totally get it ❤️

**Comment by mathbunnyru** [comment] 2023-08-28 14:22
Unfortunately, I think `Xonsh` won't help us very much.
It will definitely look nicer in some parts, like logging.
But we'll still have all the things with renaming user, and these are just calling linux user management utils like `usermod`.
On the other hand, we'll have to deal with `xonsh` vs bash differences and it'll be more difficult for the contributors to change `start.sh` (or `start.xsh`).
Here is the translation guide: https://xon.sh/bash_to_xsh.html

https://github.com/jupyter/docker-stacks/issues/1140 mentioned in the issue is solved though by using pure python scripts in [tagging dir](https://github.com/jupyter/docker-stacks/tree/main/tagging).  (and I think it works beautifully now)

So, I'm closing this issue as not planned.

**Closed by mathbunnyru** 2023-08-28 14:22 UTC
Labels: type:Enhancement, type:Maintenance
