### ISSUE TITLE
How to install a local developped package in a conda environment without root privileges

### ISSUE THREAD

**Issue by sbgsbc** [jupyter/docker-stacks#1060] opened 2020-04-08 18:16 UTC
Hello,

Following Add a Python 3.x environment everything is ok until I try to install a locally developed package (ex SBG). I add in my dockerfile :
RUN cd /home/$NB_USER/tmp/ && \
    $CONDA_DIR/envs/${conda_env}/bin/python setup.py install

So I face a problem of access :
running install
running bdist_egg
running egg_info
creating SBG.egg-info
error: could not create 'SBG.egg-info': Permission denied

How can I change privileges of the user within my dockerfile in order to allow the installation of my package ?

Many thanks

**Comment by romainx** [comment] 2020-04-09 14:07
Hello,

You can run the command as `root` in the `Dockerfile` however I'm not sure why you end with a permission error. It may break the permissions in the installation this is the reason why I have added calls to `fix-permissions`.

```dockerfile
# switch to root user
USER root
# RUN you command
WORKDIR /home/$NB_USER/tmp/ 
RUN $CONDA_DIR/envs/${conda_env}/bin/python setup.py install && \
fix-permissions $CONDA_DIR && \
fix-permissions /home/$NB_USER
# switch back to jovyan
USER $NB_UID
```

I've not tested it, so I'm not sure it will fix your problem :sweat_smile:.
Let me know.

Best.

**Comment by sbgsbc** [comment] 2020-04-10 14:42
Hello and many thanks,

First, to answer the additional question I've created the environment as follow: 
```
COPY $conda_env.txt /home/$NB_USER/tmp/
RUN cd /home/$NB_USER/tmp/ && \
     conda create --name $conda_env --file $conda_env.txt && \
     conda clean --all -f -y
```
Add USER root around the commands installing the package allows its installation within the environment, but I obtain the following error:

```
Step 6/17 : RUN $CONDA_DIR/envs/${conda_env}/bin/python -m ipykernel install --user --name=${conda_env} &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER
 ---> Running in 51ba40493b35
Installed kernelspec mp35 in /home/jovyan/.local/share/jupyter/kernels/mp35
chgrp: changing group of '/home/jovyan/tmp': Operation not permitted
chgrp: changing group of '/home/jovyan/tmp/mp35.txt': Operation not permitted
chmod: changing permissions of '/home/jovyan/tmp': Operation not permitted
```
where mp35 is my environment and mp35.txt its installation file.
Inside the container I've listed :
```
drwsrwsr-x 1 root   users 4096 Apr 10 14:22 tmp
```
It seems like /usr/local/bin/fix-permissions does nothing, am I right ?

**Comment by romainx** [comment] 2020-04-10 19:59
Hello,

I guess I've seen the root cause of this behavior. It comes from the `COPY`. If it's used like this it will create the directory `/home/$NB_USER/tmp/` and add the file as `root:root`.
To avoid all these issues you have to perform the following change.

```diff
- COPY $conda_env.txt /home/$NB_USER/tmp/
+ COPY --chown=${NB_USER}:${NB_GID} $conda_env.txt /home/$NB_USER/tmp/
```

The directory `/home/$NB_USER/tmp/` will be owned by `jovyan` and you will be OK to perform the installation without the need to switch to `root` user.

Please tell me if this change fixes your problem.

PS: Thank you for the command I will fix the doc to indicate the correct command and maybe add a word about your case.


_Note: this option is available since release Docker `v17.09.0`._

**Comment by sbgsbc** [comment] 2020-04-11 11:24
Hello,

Everything is ok now, many thanks.
Who should close the issue, me or you ?

Thanks again

De : Romain <notifications@github.com>
Répondre à : jupyter/docker-stacks <reply@reply.github.com>
Date : vendredi 10 avril 2020 à 21:59
À : jupyter/docker-stacks <docker-stacks@noreply.github.com>
Cc : BOURG Stephane <Stephane.BOURG@cnrs.fr>, Author <author@noreply.github.com>
Objet : Re: [jupyter/docker-stacks] How to install a local developped package in a conda environment without root privileges (#1060)


Hello,

I guess I've seen the root cause of this behavior. It comes from the COPY. If it's used like this it will create the directory /home/$NB_USER/tmp/ and add the file as root:root.
To avoid all these issues you have to perform the following change.

- COPY $conda_env.txt /home/$NB_USER/tmp/

+ COPY --chown=${NB_USER}:${NB_GID} $conda_env.txt /home/$NB_USER/tmp/

The directory /home/$NB_USER/tmp/ will be owned by jovyan and you will be OK to perform the installation without the need to switch to root user.

Please tell me if this change fixes your problem.

PS: Thank you for the command I will fix the doc to indicate the correct command and maybe add a word about your case.

Note: this option is available since release Docker v17.09.0.

**Comment by sbgsbc** [comment] 2020-04-11 12:41
Hello,

Everything is ok now, many thanks.
Who should close the issue, me or you ?

Thanks again

**Comment by romainx** [comment] 2020-04-11 12:44
Hello,

Great to hear that.
I'm closing the issue.

Have a nice day!

**Closed by romainx** 2020-04-11 12:44 UTC
Labels: type:Question
