### ISSUE TITLE
container id rendered instead of "localhost"

### ISSUE THREAD

**Issue by RafalSkolasinski** [jupyter/docker-stacks#666] opened 2018-07-05 17:24 UTC
**What docker image you are using?**

``jupyter/minimal-notebook:latest``

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run jupyter/minimal-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Open terminal
2. Start container
3. ...

**What do you expect to happen?**

I expect to see token preceded by ``localhost:8888``, i.e.
```
http://localhost:8888/?token=....
``` 

**What actually happens?**

Instead of l``ocalhost`` I see container ID, e.g.
```
docker run jupyter/minimal-notebook:latest                                        
/usr/local/bin/start-notebook.sh: ignoring /usr/local/bin/start-notebook.d/*

Container must be run with group "root" to update passwd file
Executing the command: jupyter notebook
[I 17:18:13.988 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 17:18:14.170 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 17:18:14.201 NotebookApp] JupyterLab beta preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 17:18:14.201 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 17:18:14.207 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 17:18:14.207 NotebookApp] 0 active kernels
[I 17:18:14.207 NotebookApp] The Jupyter Notebook is running at:
[I 17:18:14.207 NotebookApp] http://f29f5e6ec737:8888/?token=e334b8d7353658d2b6287c1e53abf342106a60a5b38e6ea2
[I 17:18:14.207 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:18:14.208 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://f29f5e6ec737:8888/?token=e334b8d7353658d2b6287c1e53abf342106a60a5b38e6ea2&token=e334b8d7353658d2b6287c1e53abf342106a60a5b38e6ea2
```

**Comment by parente** [comment] 2018-07-05 17:55
Closing as a duplicate of #642 which includes a discussion about the upstream change in jupyter/notebook, documentation that was updated here to account for this change, and the behavior of containers. 

Reusing @minrk' summary: In general, the URL has never been valid because the container doesn't know the external port or ip. It happened to be right if you did the following:

* run docker locally (no docker-machine, etc.)
* forward the same port (8888:8888), never map different ports

Unfortunately, it's impossible for the container to know if either of these is the case, so the only reliable information that should be copied is the `?token=...` part of the URL when the notebook is run in a container.

**Closed by parente** 2018-07-05 17:55 UTC
