### ISSUE TITLE
org.apache.spark.api.python.PythonException; local class incompatible

### ISSUE THREAD

**Issue by luminousmen** [jupyter/docker-stacks#945] opened 2019-10-01 20:27 UTC
I'm trying to use jupyter/all-spark-notebook with an external standalone spark cluster. Got the error while doing a simple script:

```import os
import pyspark
conf = pyspark.SparkConf()

conf.setMaster("spark://172.19.0.2:7077")
sc = pyspark.SparkContext(conf=conf)
rdd = sc.parallelize(range(1000))
rdd.take(3)
```
Error:
```java.io.InvalidClassException: org.apache.spark.api.python.PythonException; local class incompatible: stream classdesc serialVersionUID = 5540028395182668829, local class serialVersionUID = -216573626675865439```

I'm using docker images as part of docker-compose, usage below:
```
jupyter:
    build: ./docker/jupyter/
    ports:
      - "8888:8888"
    network_mode: host
    pid: "host"
    environment:
      - "TINI_SUBREAPER=true"
      - "APACHE_SPARK_VERSION=2.4.3"
```
Thanks in advance!

**Comment by romainx** [comment] 2020-02-08 20:14
Hello,

To be able to run Spark with an external cluster you have to use exactly the same versions on both driver (the Jupyter notebook) and the cluster.

According to the error message, I think it's the cause of the problem. 
You seem to use a Spark `2.4.3` in your cluster (`docker-compose`) please check that the version is the same in the notebook. At this time the version used is `2.4.4`.

```
jovyan@ab2f6f1cd153:~$ echo $APACHE_SPARK_VERSION 
2.4.4
```

# Notes

If you plan to use `Pyspark` you will also have to use the same Python versions on both sides.

Hope it helps.

Best.

**Comment by mathbunnyru** [comment] 2021-05-06 23:43
@luminousmen could you please tell us if this answer helped you?

**Comment by mathbunnyru** [comment] 2021-05-09 19:47
Great. Then I'm closing this issue.

**Closed by mathbunnyru** 2021-05-09 19:47 UTC
Labels: status:Need Info
