### ISSUE TITLE
Troubling connecting to internet from docker container

### ISSUE THREAD

**Issue by sivakon** [jupyter/docker-stacks#493] opened 2017-11-07 09:31 UTC
Hi,

I am trying to use spark-notebook, but I get an error while downloading packages to my Apache Toree kernel. Python kernel works fine.

**What docker image you are using?**

`jupyter/all-spark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8888
2. Start Toree kernel
3. `scala.io.Source.fromURL("https://www.google.com").mkString` 

The last command does not work.

**What do you expect to happen?**

Example: Status 200

**What actually happens?**

Connection gets timed out.

Error message in the console:
```
Name: java.nio.charset.MalformedInputException
Message: Input length = 1
StackTrace:   at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
  at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
  at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
  at java.io.InputStreamReader.read(InputStreamReader.java:184)
  at java.io.BufferedReader.read1(BufferedReader.java:210)
  at java.io.BufferedReader.read(BufferedReader.java:286)
  at java.io.Reader.read(Reader.java:140)
  at scala.io.BufferedSource.mkString(BufferedSource.scala:96)
```

**Comment by blacknred0** [comment] 2017-11-07 20:25
Are you importing other functions?

I try running that command and got a different error.
```
Name: java.nio.charset.MalformedInputException
Message: Input length = 1
StackTrace:   at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
  at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
  at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
  at java.io.InputStreamReader.read(InputStreamReader.java:184)
  at java.io.BufferedReader.read1(BufferedReader.java:210)
  at java.io.BufferedReader.read(BufferedReader.java:286)
  at java.io.Reader.read(Reader.java:140)
  at scala.io.BufferedSource.mkString(BufferedSource.scala:96)
```

**Comment by sivakon** [comment] 2017-11-08 00:01
@blacknred0 I got the same error. Some problem with Toree, I'm trying from scratch (base-notebook).

**Comment by blacknred0** [comment] 2017-11-08 14:19
@sivakon I also tested straight from scala (on spark 2.2.0) and got the same error.

**Comment by parente** [comment] 2017-11-11 04:20
It's possible that Toree is not compatible with Spark 2.2.0. IIRC, the last incubation release was made for Spark 2.0.0.

**Comment by blacknred0** [comment] 2017-11-12 20:31
I don't think this is a Toree issue, but rather scala.

**Comment by parente** [comment] 2017-12-19 14:25
@sivakon @blacknred0 It looks like your investigations have lead you to think Scala is the issue here. Should we keep this issue open (i.e., is it only occurring when using Scala in the docker images built here) or close it as a problem that will be fixed when the problem is resolved upstream?

**Comment by sivakon** [comment] 2017-12-27 12:25
@parente I built Apache toree from source. Now, it works like charm.

**Comment by parente** [comment] 2017-12-28 01:51
@sivakon Thanks for the feedback. Sounds like it's fixed in Toree master branch, and maybe in the 0.2.0 release candidate builds. Leaving this issue open as a reminder to update the Toree version once 0.2.0 final is out.

**Closed** 2018-01-05 12:14 UTC
Labels: dependency
