### ISSUE TITLE
NB_USER is not applied in docker run

### ISSUE THREAD

**Issue by marcraminv** [jupyter/docker-stacks#707] opened 2018-08-26 12:17 UTC
**What docker image you are using?**

`jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**
 
```
docker run \
--rm \
-it \
--name jupyter \
-p 8888:8888 \
-e NB_USER=marc \
jupyter/scipy-notebook:latest
```

 **What steps do you take once the container is running to reproduce the issue?**

1. docker run to power the container:
```
docker run \
--rm \
-it \
--name jupyter \
-p 8888:8888 \
-e NB_USER=marc \
jupyter/scipy-notebook:latest
```
The console output:
![1](https://user-images.githubusercontent.com/13021787/44628012-b3868380-a938-11e8-899a-6c13453a9c6c.png)

2. `docker exec -it jupyter /bin/bash`
console output:
![2](https://user-images.githubusercontent.com/13021787/44628013-b8e3ce00-a938-11e8-992f-2f06353099eb.png)

3. `env`

console ouput:
![3](https://user-images.githubusercontent.com/13021787/44628016-c39e6300-a938-11e8-89ec-29b501d73ea0.png)

4. docker run with `root` user:
```
docker run \
--rm \
-it \
--name jupyter \
-p 8888:8888 \
-e NB_USER=marc \
--user root \
jupyter/scipy-notebook:latest
```
console output:
![4](https://user-images.githubusercontent.com/13021787/44628025-e761a900-a938-11e8-8ce5-c0dd093d3f25.png)

5. `docker exec -it jupyter /bin/bash`

console output:
![5](https://user-images.githubusercontent.com/13021787/44628026-edf02080-a938-11e8-8024-aaa511964247.png)

**What do you expect to happen?**

The user `marc` should be changed by joyan as documentation says.
![6](https://user-images.githubusercontent.com/13021787/44628100-1cbac680-a93a-11e8-8611-f295b7be81b0.png)

**What actually happens?**

The start script does not apply **NB_USER**. I don't know if I understood something wrong reading the documentation, but I thought that something was wrong with start script and permissions set up.

**Comment by parente** [comment] 2018-08-26 16:47
The documentation is missing the key sentence that appears next to the `NB_UID` and other options that modify the default user:

> For this option to take effect, you must run the container with --user root.

Sorry for the trouble. Happy to take a PR to update that bullet in the docs if you'd like to contribute the fix. If not, we'll get to it!

**Comment by marcraminv** [comment] 2018-08-26 18:35
Thanks for response @parente , but if you see the point 5, If I run the the image with this:
```
docker run \
--rm \
-it \
--name jupyter \
-p 8888:8888 \
-e NB_USER=marc \
--user root \
jupyter/scipy-notebook:latest
```
then, I cannot access to the container. 
Do I forget something? For me seems a bug, but I am not sure  if I forget any additional config.

**Comment by parente** [comment] 2018-08-26 23:00
Ah, sorry, I missed the `--user root` in the command before the exec. The problem with the `exec` in step #5 is that because the user name has changed, the working directory configured in the Dockerfile is no longer valid.

This command will work:

```
docker exec -it -w /home/marc jupyter /bin/bash
```

The `start-notebook.sh` script avoids this problem by adjusting the working dir for the notebook server when handling the `NB_USER` change, but that has no effect on the container configuration itself.

**Comment by marcraminv** [comment] 2018-08-28 07:39
I understand that it happens because the **HOME** directory is pointing to the `/home/jovyan` although the directory doesn't already exist. I checked the `env` and I see that:
<img width="576" alt="screen shot 2018-08-28 at 09 26 25" src="https://user-images.githubusercontent.com/13021787/44707797-c9fe1d80-aaa5-11e8-90f6-6f09765f0dc1.png">

So... If someone try to mount a volume in docker to his custom home, it will not be possible, right @parente ?

**Comment by edesz** [comment] 2018-09-16 17:51
Thanks @parente for [your tip](https://github.com/jupyter/docker-stacks/issues/707#issuecomment-416079232) to specify the working directory. This was really helpful. I too could not use [a custom name for `NB_USER`](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options) initially. But with the specification of `-w` flag, I can confirm that the custom user is now working for me. 

**Custom user**
If I used a custom user (not `jovyan`) with the specification of the working directory

`...-w /home/<myuser> jupyter`

as suggested [above](https://github.com/jupyter/docker-stacks/issues/707#issuecomment-416079232), then it works for me. It set my working directory to `/home/<myuser>` and the jupyter tree opens directly at `/home/<myuser>`.

**Mounting volumes to custom user's home**
Then I also tried to mount a volume to the custom user's home by specifying the `-v` flag

`...-w /home/<myuser> -v ~/work:/home/<myuser> jupyter`

and this also worked as expected - I could see all the contents of `~/work` (on my local host) inside the docker container at `/home/<myuser>`.

**Comment by marcraminv** [comment] 2018-09-16 19:54
thanks @edesz! I tried only for execute the `docker exec` command and it works, but I didn't try with the `run` command. I think that this could be a good use case to make the PR to docs.

**Comment by parente** [comment] 2018-12-29 15:42
Docs updated by PR #723. Closing this out.

**Closed by parente** 2018-12-29 15:42 UTC
Labels: tag:Documentation, type:Bug
