### ISSUE TITLE
[BUG] start by singleuser doesn't has bashrc properly set in user folder

### ISSUE THREAD

**Issue by unkcpz** [jupyter/docker-stacks#1848] opened 2022-12-16 13:15 UTC
### What docker image(s) are you using?

minimal-notebook

### OS system and architecture running docker image

Ubuntu 18.04 amd64

### What Docker command are you running?

```yaml
---
singleuser:
    image:
        name: "docker.io/jupyter/minimal-notebook"      
        tag: "python-3.9.13"
        pullPolicy: "Always"
    extraEnv:
        DOCKER_STACKS_JUPYTER_CMD: "notebook"
        #JUPYTERHUB_SINGLEUSER_APP: "notebook.notebookapp.NotebookApp"
    storage:
        dynamic:
            storageClass: aiidalab-storage
...
```

### How to Reproduce the problem?

1. open the container spawned (I use microk8s in my deployment). 
2. It is still running the lab mode, which I expect the notebook since I set `DOCKER_STACKS_JUPYTER_CMD=notebook`
3. Also run `ls -al`, there is no `.bashrc` in the user home folder.

### Expected behavior

The entity start at notebook mode and the `.bashrc` setting is not being wiped out.

### Actual behavior

It is all fine if I run the container without `JUPYTHERHUB_API_TOKEN` by docker run in my local machine. But spawn the user by spawner, the `JUPYTERHUB_API_TOKEN` will shift to `start-singleuser.sh` (as https://github.com/jupyter/docker-stacks/blob/f60eda163f9164e5264335933dfeddd04323450c/base-notebook/start-notebook.sh#L11-L14 here indicated).

Is there anything run in my `singleuser` setting?

**Comment by mathbunnyru** [comment] 2023-08-20 13:54
Hi @unkcpz.
Sorry for the late response.

`DOCKER_STACKS_JUPYTER_CMD` is indeed only for non-jupyterhub.
You can use [these docs](https://jupyterhub.readthedocs.io/en/latest/howto/configuration/config-user-env.html#switching-back-to-the-classic-notebook) to switch the command.
Hope this helps.
I also described this in our docs: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#switching-back-to-the-classic-notebook-or-using-a-different-startup-command

`.bashrc` being wiped is a duplicate of the following issue (which has been with us for many years): https://github.com/jupyter/docker-stacks/issues/815

**Comment by mathbunnyru** [comment] 2023-08-20 13:55
I'm closing this issue (actually 2 issues) - there is a solution for the first issue and it's documented, and the second one is a duplicate.
Please, let me know, if I got something wrong.

**Closed by mathbunnyru** 2023-08-20 13:55 UTC
Labels: type:Bug
