### ISSUE TITLE
Add Dockerfile for aarch64 (arm64/v8) 

### ISSUE THREAD

**Issue by akitanaka** [jupyter/docker-stacks#1050] opened 2020-03-24 03:33 UTC
Hello.

I'm wondering it would be great if we can add base-notebook Dockerfile for aarch64 platform and the community can provide the official Docker image on [Docker Hub](https://hub.docker.com/layers/ubuntu/library/ubuntu/bionic-20200219/images/sha256-fab7c78ecd4c52e801b8a597846ec5c00ff2e4f4d1d92f6af1c8390eabc1d2d5?context=explore).

The Dockerfile would be like below (I haven't created the pull request yet since this would be new feature request and want to get the comment from community first.):
https://gist.github.com/akitanaka/e6d8f3550d9179d006e0d787d4a1b3e7
(Copied base-notebook Dockerfile and just replaced the miniconda repo url with the miniforge url)

Since some platform like RedHat and AWS support the aarch64 architecture, many users will get the benefit from providing the Dockerfile.

This would be new feature request. If it's required, I think I can help to test and maintain the Docker image.

Thank you.

**What docker image you are using?**

Example: `jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

N/A

**What steps do you take once the container is running to reproduce the issue?**

N/A

**What do you expect to happen?**

N/A

**What actually happens?**

N/A

**Comment by step21** [comment] 2020-06-09 11:38
As stated in the docs, this will probably not be merged. But I made some docker images here
https://hub.docker.com/repository/docker/step21/jupyter-minimal-notebook (under arm64 tag)
(base and minimal until scikit-image is merged into conda-forge for aarch64)
The aarch64 ones are at least much closer to standard images.

**Comment by parente** [comment] 2020-06-13 18:01
I think links to one or both of these resources would be great additions to the [community stacks section in the documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#community-stacks).

**Comment by step21** [comment] 2020-06-14 12:12
Thanks. Any pull requests etc welcome. If you want to help to get proper juypter stacks, you could also help packaging for conda-forge. The only package holding back a scipy notebook right now is numba which needs llvm.

**Comment by consideRatio** [comment] 2021-05-02 10:58
In the JupyterHub organization on GitHub, we have now published (thanks @manics!!!) arm64/aarch64 compatible images alongside the amd64/x86_64 for multiple repositories.

I would like to help this repo do the same, but at the same time I find it crucial that future maintenance is sustainable. I created the enhancement proposal below with that in mind.

### Enhancement proposal

1. Principle - to maintain only a single Dockerfile per image
2. Action - to remove the dedicated and outdated ppc64le Dockerfiles and `.patch` files
3. Implementation detail - maintain a list of the images' compatible architectures
4. Action - update the Makefile to be able to, in an opt-in fashion, to build the same Dockerfile for all compatible architectures (like in: [Z2JH](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/b804bac3ad6acf8b656f6108a5a18b95d9d22c10/.github/workflows/publish.yml#L60-L68), [JupyterHub](https://github.com/jupyterhub/jupyterhub/blob/3fec19d191119e4203c243f44c43e74c8fe62f04/.github/workflows/release.yml#L96-L142), [ConfigurableHTTPProxy](https://github.com/jupyterhub/configurable-http-proxy/blob/9bcabb140e7cc534ca0b9a31ebb146d1e6c82786/.github/workflows/publish.yml#L31-L79))

### Current arm64/aarch64 compatibility status

I went ahead and tried building all Dockerfile's (no patches applied etc) with `--platform linux/arm64` using `docker buildx` instead of `docker` and created this arm64 compatibility list.

- [x] base-notebook
- [x] minimal-notebook
- [ ] r-notebook
  `conda` can't resolve/install r packages
- [x] scipy-notebook
- [ ] tensorflow-notebook
  `conda` can't install tensorflow of pinned version
- [ ] datascience-notebook
  - hardcoded x86_64 installation of julia
  - `conda` can't resolve/install r packages
- [x] pyspark-notebook
- [ ] all-spark-notebook

**Comment by manics** [comment] 2021-05-02 16:32
Looks like this issue is another duplicate of https://github.com/jupyter/docker-stacks/issues/1019 which has contributions from others. How about moving the discussion there so as not to split things?

**Comment by consideRatio** [comment] 2021-05-02 16:41
I'm moving my comment to that issue :P

**Comment by mathbunnyru** [comment] 2021-05-03 11:29
@akitanaka @step21 @manics @consideRatio @parente I'm closing this issue as a duplicate of https://github.com/jupyter/docker-stacks/issues/1019 to make it easy to have everything in one place.
I think the interest is growing in multi-arch images (especially, `aarch64`), so as mentioned here it's better not to split things.

**Closed by mathbunnyru** 2021-05-03 11:29 UTC
Labels: status:Duplicate, tag:Documentation, type:Enhancement
