### ISSUE TITLE
jupyter/base-notebook: Installing additional packages with pip

### ISSUE THREAD

**Issue by lima4658** [jupyter/docker-stacks#1305] opened 2021-05-15 22:45 UTC
Several python packages have to be recompiled when using pip for installation.

This will fail due to missing compiler infrastructure of the OS (e.g. pip install bottleneck)

Solution:
add Ubuntu packages 'build-essential binutils binfmt-support' to the first RUN statement of the Dockerfile

**Comment by mathbunnyru** [comment] 2021-05-20 12:59
Thanks for the suggestion @lima4658.

Though you suggestion will make installation of some packages easier, it will increase the image size even for those, who are only using our images and not installing much on top (or installing regular python packages without building).

And, I think, if people need a package with compiler infrastructure of the OS, they can manage to install it themselves.

**Comment by mathbunnyru** [comment] 2021-05-21 15:29
As this is not a bug and intended behaviour, closing this issue.

**Closed by mathbunnyru** 2021-05-21 15:29 UTC
