### ISSUE TITLE
R-Kernel is dead 

### ISSUE THREAD

**Issue by 9404368350** [jupyter/docker-stacks#381] opened 2017-05-12 05:16 UTC
After building the jupyterhub R image from Dockerfile provided r-notebook directory. R kernel is not working properly it gives the error R-kernel is dead and restart the kernel several times.

**Comment by parente** [comment] 2017-05-12 16:05
I am unable to reproduce with the latest image pushed to Docker Hub. 

![screen shot 2017-05-12 at 12 05 03 pm](https://cloud.githubusercontent.com/assets/153745/26006662/48be46e6-370b-11e7-8971-022b9525a64c.png)

Can you share what git sha you're building, the command you're using to rebuild it, and what modifications if any you've made to the r-notebook dockerfile?

**Comment by 9404368350** [comment] 2017-05-14 06:36
I didn't make any changes in the docker file.
Give me the name of the image so I can directly pull it from the dockerhub

**Comment by parente** [comment] 2017-06-25 16:15
The Basic Use section of the [README in the r-notebook subfolder](https://github.com/jupyter/docker-stacks/tree/master/r-notebook#basic-use) gives the docker run command including the image name that it will pull from the Hub if you do not already have a copy locally. The other images are similarly named and documented.

I'm going to close this ticket as "can't reproduce." If you find that the image on docker hub exhibits the same behavior when you pull and run it, feel free to reopen this issue.

**Closed by parente** 2017-06-25 16:15 UTC
Labels: need info
