### ISSUE TITLE
`Jupyter/r-notebook` instance cannot show base `R` plot

### ISSUE THREAD

**Issue by karenyyng** [jupyter/docker-stacks#271] opened 2016-08-30 21:50 UTC
The Jupyter notebook with a R kernel cannot show baseR plots correctly.
The commit tag of the image that I run is be04e277aae4ae9c655a033f1b80c9ea8fb110fd.
This issue exists for the docker images`Jupyter/r-notebook` and `Jupyter/datascience-notebook` for me.

![screen shot 2016-08-30 at 2 44 21 pm](https://cloud.githubusercontent.com/assets/3587616/18108245/4f83c03c-6ec0-11e6-899f-393a9b756baa.png)

@takluyver Should I open an issue in this repo or in the IRkernel/IRkernel repo?
I can confirm that plotting works for my local installation of Jupyter via Conda on my Macbook air.

I do not see any error messages from the Jupyter kernel within the docker container other than the message `plot without title`. I appreciate any pointers for debugging and will be happy to help fix the bug.

**Comment by parente** [comment] 2016-08-31 01:32
Hi karenyyng. This has been a recurring issue tracked in #210. You can see the history of fixes and regressions in there. I haven't had time to play with the image to see what the problem is this time. The last fix required pinning the version of libjpeg. Maybe that pinned version is now causing the problem rather than resolving it.

If you do decide to tackle this, we'll certainly take a PR. Let's continue the conversation in the existing issue.

**Closed by parente** 2016-08-31 01:32 UTC

**Comment by karenyyng** [comment] 2016-08-31 02:01
Thanks @parente for the quick response. I will take a look at #210.
