### ISSUE TITLE
pyspark: undefined symbol in pyarrow

### ISSUE THREAD

**Issue by dungdm93** [jupyter/docker-stacks#966] opened 2019-12-05 04:22 UTC
**What docker image you are using?**

`jupyter/pyspark-notebook`

**Steps**

```console
dungdm93@localhost:~$ docker run -it jupyter/pyspark-notebook bash
jovyan@2c64156fbae6:~$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/__init__.py", line 54, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /opt/conda/lib/python3.7/site-packages/pyarrow/lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK5arrow6Status8ToStringB5cxx11Ev
>>>
```

The error say that:
```log
ImportError: /opt/conda/lib/python3.7/site-packages/pyarrow/lib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK5arrow6Status8ToStringB5cxx11Ev
```

**Comment by Bidek56** [comment] 2019-12-06 18:01
Please see https://github.com/jupyter/docker-stacks/issues/944 for resolution but because of a Conda issue, PR won't build and the issue can not be resolved at this time.

**Comment by parente** [comment] 2020-01-20 04:47
Thanks for reporting @dungdm93. I'm going to close this issue as a duplicate of #944.

**Closed by parente** 2020-01-20 04:47 UTC
